[phases.setup]
nixPkgs = [
  "nodejs_22", 
  "chromium",
  "glib",
  "nss",
  "nspr", 
  "fontconfig",
  "freetype",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXext",
  "xorg.libXrandr",
  "gtk3",
  "alsa-lib",
  "mesa"
]

[start]
cmd = "node ./dist/server.js"

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "chromium"