import { ServerOptions } from './types/ServerOptions';

export default {
  secretKey: process.env.SECRET_KEY || 'THISISMYSECURETOKEN',
  host: process.env.HOST || 'http://localhost',
  port: process.env.PORT || '21465',
  deviceName: process.env.DEVICE_NAME || 'WppConnect',
  poweredBy: 'WPPConnect-Server',
  startAllSession: process.env.START_ALL_SESSIONS === 'true' || true,
  tokenStoreType: 'file',
  maxListeners: parseInt(process.env.MAX_LISTENERS || '15'),
  customUserDataDir: './userDataDir/',
  webhook: {
    url: process.env.WEBHOOK_URL || null,
    autoDownload: process.env.WEBHOOK_AUTO_DOWNLOAD !== 'false',
    uploadS3: process.env.WEBHOOK_UPLOAD_S3 === 'true',
    readMessage: process.env.WEBHOOK_READ_MESSAGE !== 'false',
    allUnreadOnStart: process.env.WEBHOOK_ALL_UNREAD_ON_START === 'true',
    listenAcks: process.env.WEBHOOK_LISTEN_ACKS !== 'false',
    onPresenceChanged: process.env.WEBHOOK_ON_PRESENCE_CHANGED !== 'false',
    onParticipantsChanged: process.env.WEBHOOK_ON_PARTICIPANTS_CHANGED !== 'false',
    onReactionMessage: process.env.WEBHOOK_ON_REACTION_MESSAGE !== 'false',
    onPollResponse: process.env.WEBHOOK_ON_POLL_RESPONSE !== 'false',
    onRevokedMessage: process.env.WEBHOOK_ON_REVOKED_MESSAGE !== 'false',
    onLabelUpdated: process.env.WEBHOOK_ON_LABEL_UPDATED !== 'false',
    onSelfMessage: process.env.WEBHOOK_ON_SELF_MESSAGE === 'true',
    ignore: ['status@broadcast'],
  },
  websocket: {
    autoDownload: process.env.WEBSOCKET_AUTO_DOWNLOAD === 'true',
    uploadS3: process.env.WEBSOCKET_UPLOAD_S3 === 'true',
  },
  chatwoot: {
    sendQrCode: process.env.CHATWOOT_SEND_QR_CODE !== 'false',
    sendStatus: process.env.CHATWOOT_SEND_STATUS !== 'false',
  },
  archive: {
    enable: process.env.ARCHIVE_ENABLE === 'true',
    waitTime: parseInt(process.env.ARCHIVE_WAIT_TIME || '10'),
    daysToArchive: parseInt(process.env.ARCHIVE_DAYS_TO_ARCHIVE || '45'),
  },
  log: {
    level: process.env.LOG_LEVEL || 'silly',
    logger: (process.env.LOG_LOGGER || 'console,file').split(','),
  },
  createOptions: {
    browserArgs: [
      '--disable-web-security',
      '--no-sandbox',
      '--disable-web-security',
      '--aggressive-cache-discard',
      '--disable-cache',
      '--disable-application-cache',
      '--disable-offline-load-stale-cache',
      '--disk-cache-size=0',
      '--disable-background-networking',
      '--disable-default-apps',
      '--disable-extensions',
      '--disable-sync',
      '--disable-dev-shm-usage',
      '--disable-gpu',
      '--disable-translate',
      '--hide-scrollbars',
      '--metrics-recording-only',
      '--mute-audio',
      '--no-first-run',
      '--safebrowsing-disable-auto-update',
      '--ignore-certificate-errors',
      '--ignore-ssl-errors',
      '--ignore-certificate-errors-spki-list',
    ],
    linkPreviewApiServers: null,
  },
  mapper: {
    enable: process.env.MAPPER_ENABLE === 'true',
    prefix: process.env.MAPPER_PREFIX || 'tagone-',
  },
  db: {
    mongodbDatabase: process.env.MONGODB_DATABASE || 'tokens',
    mongodbCollection: process.env.MONGODB_COLLECTION || '',
    mongodbUser: process.env.MONGODB_USER || '',
    mongodbPassword: process.env.MONGODB_PASSWORD || '',
    mongodbHost: process.env.MONGODB_HOST || '',
    mongoIsRemote: process.env.MONGODB_IS_REMOTE === 'true',
    mongoURLRemote: process.env.MONGODB_URL_REMOTE || '',
    mongodbPort: parseInt(process.env.MONGODB_PORT || '27017'),
    redisHost: process.env.REDIS_HOST || 'localhost',
    redisPort: parseInt(process.env.REDIS_PORT || '6379'),
    redisPassword: process.env.REDIS_PASSWORD || '',
    redisDb: parseInt(process.env.REDIS_DB || '0'),
    redisPrefix: process.env.REDIS_PREFIX || 'docker',
  },
  aws_s3: {
    region: (process.env.AWS_S3_REGION || 'sa-east-1') as any,
    access_key_id: process.env.AWS_S3_ACCESS_KEY_ID || null,
    secret_key: process.env.AWS_S3_SECRET_KEY || null,
    defaultBucketName: process.env.AWS_S3_DEFAULT_BUCKET_NAME || null,
    endpoint: process.env.AWS_S3_ENDPOINT || null,
    forcePathStyle: process.env.AWS_S3_FORCE_PATH_STYLE === 'true' || null,
  },
} as unknown as ServerOptions;